# Generated by Django 2.2 on 2020-09-13 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_no', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'UserDetails',
                'ordering': ['phone'],
            },
        ),
    ]
