# Generated by Django 2.2 on 2020-09-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_batch_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
