# Generated by Django 2.2 on 2020-09-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_course_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
