# Generated by Django 2.2 on 2020-09-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200919_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
