# Generated by Django 2.2 on 2020-09-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('App', '0007_auto_20200919_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('userimage', models.ImageField(upload_to='UserImage/')),
            ],
        ),
    ]
